export type { ModalProps, ModalDefinition } from './types'
export { ModalRegistry } from './registry'
export { build } from './build'
export { useModalContainerPosition } from './hooks/use-modal-container-position'
export * from './components'
